from typing import List


class ParseResult:
    @property
    def pattern_count(self) -> int: ...
    @property
    def identifiers(self) -> List[str]: ...


def parse_gram(input: str) -> ParseResult: ...
def validate_gram(input: str) -> bool: ...
def round_trip(input: str) -> str: ...
