from __future__ import annotations

from relateby.pattern import Pattern
from relateby.pattern._subject import Subject


class GramParseError(Exception):
    @property
    def input(self) -> str: ...
    @property
    def cause(self) -> str: ...


def parse(input: str) -> list[Pattern[Subject]]: ...
def stringify(patterns: list[Pattern[Subject]]) -> str: ...
def parse_with_header(input: str) -> tuple[dict | None, list[Pattern[Subject]]]: ...
def stringify_with_header(
    header: dict | None, patterns: list[Pattern[Subject]]
) -> str: ...
def gram_validate(input: str) -> list[str]: ...
def round_trip(input: str) -> str: ...

# Legacy aliases
parse_gram = parse
gram_stringify = stringify
