from __future__ import annotations

from relateby.pattern import Pattern
from relateby.pattern._subject import Subject


class GramParseError(Exception):
    @property
    def input(self) -> str: ...
    @property
    def cause(self) -> str: ...


def parse_gram(input: str) -> list[Pattern[Subject]]: ...
def gram_stringify(patterns: list[Pattern[Subject]]) -> str: ...
def gram_validate(input: str) -> list[str]: ...
def round_trip(input: str) -> str: ...
