from typing import Any, Callable, Dict, List, Optional, Set, TypeVar, Union

T = TypeVar("T")


class Value:
    @staticmethod
    def string(value: str) -> Value: ...
    @staticmethod
    def int(value: int) -> Value: ...
    @staticmethod
    def decimal(value: float) -> Value: ...
    @staticmethod
    def boolean(value: bool) -> Value: ...
    @staticmethod
    def symbol(value: str) -> Value: ...
    @staticmethod
    def array(items: List[Any]) -> Value: ...
    @staticmethod
    def map(items: Dict[str, Any]) -> Value: ...
    @staticmethod
    def range(lower: Optional[float] = ..., upper: Optional[float] = ...) -> Value: ...
    @staticmethod
    def measurement(value: float, unit: str) -> Value: ...
    def as_string(self) -> str: ...
    def as_int(self) -> int: ...
    def as_decimal(self) -> float: ...
    def as_boolean(self) -> bool: ...
    def as_array(self) -> List[Any]: ...
    def as_map(self) -> Dict[str, Any]: ...


class Subject:
    def __init__(
        self,
        identity: str,
        labels: Optional[Set[str]] = ...,
        properties: Optional[Dict[str, Union[Value, str, int, float, bool, list, dict]]] = ...,
    ) -> None: ...
    @property
    def identity(self) -> str: ...
    def get_labels(self) -> Set[str]: ...
    def get_properties(self) -> Dict[str, Any]: ...
    def add_label(self, label: str) -> None: ...
    def remove_label(self, label: str) -> None: ...
    def has_label(self, label: str) -> bool: ...
    def get_property(self, name: str) -> Optional[Value]: ...
    def set_property(self, name: str, value: Union[Value, str, int, float, bool, list, dict]) -> None: ...
    def remove_property(self, name: str) -> None: ...
    @staticmethod
    def from_id(identity: str) -> Subject: ...
    @staticmethod
    def build(identity: str) -> SubjectBuilder: ...


class Pattern:
    @staticmethod
    def point(value: Any) -> Pattern: ...
    @staticmethod
    def pattern(value: Any, elements: List[Pattern]) -> Pattern: ...
    @staticmethod
    def of(value: Any) -> Pattern: ...
    @staticmethod
    def from_values(values: List[Any]) -> List[Pattern]: ...
    @property
    def value(self) -> Any: ...
    @property
    def elements(self) -> List[Pattern]: ...
    def is_atomic(self) -> bool: ...
    def length(self) -> int: ...
    def size(self) -> int: ...
    def depth(self) -> int: ...
    def values(self) -> List[Any]: ...
    def any_value(self, predicate: Callable[[Any], bool]) -> bool: ...
    def all_values(self, predicate: Callable[[Any], bool]) -> bool: ...
    def filter(self, predicate: Callable[[Pattern], bool]) -> List[Pattern]: ...
    def find_first(self, predicate: Callable[[Pattern], bool]) -> Optional[Pattern]: ...
    def matches(self, other: Pattern) -> bool: ...
    def contains(self, other: Pattern) -> bool: ...
    def map(self, func: Callable[[Any], Any]) -> Pattern: ...
    def fold(self, init: Any, func: Callable[[Any, Any], Any]) -> Any: ...
    def para(self, func: Callable[[Pattern, List[T]], T]) -> T: ...
    def combine(self, other: Pattern) -> Pattern: ...
    def extract(self) -> Any: ...
    def extend(self, func: Callable[[Pattern], Any]) -> Pattern: ...
    def depth_at(self) -> Pattern: ...
    def size_at(self) -> Pattern: ...
    def indices_at(self) -> Pattern: ...
    def validate(self, rules: ValidationRules) -> None: ...
    def analyze_structure(self) -> StructureAnalysis: ...


class ValidationRules:
    def __init__(self, max_depth: Optional[int] = ..., max_elements: Optional[int] = ...) -> None: ...
    @property
    def max_depth(self) -> Optional[int]: ...
    @property
    def max_elements(self) -> Optional[int]: ...


class ValidationError(ValueError):
    @property
    def message(self) -> str: ...
    @property
    def rule(self) -> str: ...
    @property
    def location(self) -> List[str]: ...


class StructureAnalysis:
    @property
    def summary(self) -> str: ...
    @property
    def depth_distribution(self) -> List[int]: ...
    @property
    def element_counts(self) -> List[int]: ...
    @property
    def nesting_patterns(self) -> List[str]: ...


class SubjectBuilder:
    def label(self, label: str) -> SubjectBuilder: ...
    def property(self, key: str, value: Union[Value, str, int, float, bool, list, dict]) -> SubjectBuilder: ...
    def done(self) -> Subject: ...


class StandardGraph:
    def __init__(self) -> None: ...
    @staticmethod
    def from_patterns(patterns: List[Pattern]) -> StandardGraph: ...
    @classmethod
    def from_gram(cls, input: str) -> StandardGraph: ...
    def add_node(self, subject: Subject) -> StandardGraph: ...
    def add_relationship(self, subject: Subject, source: Subject, target: Subject) -> StandardGraph: ...
    def add_walk(self, subject: Subject, relationships: List[Subject]) -> StandardGraph: ...
    def add_annotation(self, subject: Subject, element: Subject) -> StandardGraph: ...
    def add_pattern(self, pattern: Pattern) -> StandardGraph: ...
    def node(self, id: str) -> Optional[Pattern]: ...
    def relationship(self, id: str) -> Optional[Pattern]: ...
    def walk(self, id: str) -> Optional[Pattern]: ...
    def annotation(self, id: str) -> Optional[Pattern]: ...
    @property
    def node_count(self) -> int: ...
    @property
    def relationship_count(self) -> int: ...
    @property
    def walk_count(self) -> int: ...
    @property
    def annotation_count(self) -> int: ...
    @property
    def is_empty(self) -> bool: ...
    @property
    def has_conflicts(self) -> bool: ...
    def nodes(self) -> List[tuple[str, Pattern]]: ...
    def relationships(self) -> List[tuple[str, Pattern]]: ...
    def walks(self) -> List[tuple[str, Pattern]]: ...
    def annotations(self) -> List[tuple[str, Pattern]]: ...
    def source(self, rel_id: str) -> Optional[Pattern]: ...
    def target(self, rel_id: str) -> Optional[Pattern]: ...
    def neighbors(self, node_id: str) -> List[Pattern]: ...
    def degree(self, node_id: str) -> int: ...
