from __future__ import annotations

from typing import Any, Callable, Generic, Iterator, Optional, TypeVar, Union, overload

V = TypeVar("V")
U = TypeVar("U")
R = TypeVar("R")
A = TypeVar("A")


class StringVal:
    value: str
    def __init__(self, value: str) -> None: ...


class IntVal:
    value: int
    def __init__(self, value: int) -> None: ...


class FloatVal:
    value: float
    def __init__(self, value: float) -> None: ...


class BoolVal:
    value: bool
    def __init__(self, value: bool) -> None: ...


class NullVal:
    def __init__(self) -> None: ...


class SymbolVal:
    value: str
    def __init__(self, value: str) -> None: ...


class TaggedStringVal:
    tag: str
    content: str
    def __init__(self, tag: str, content: str) -> None: ...


class ArrayVal:
    items: list["Value"]
    def __init__(self, items: list["Value"]) -> None: ...


class MapVal:
    entries: dict[str, "Value"]
    def __init__(self, entries: dict[str, "Value"]) -> None: ...


class RangeVal:
    lower: Optional[float]
    upper: Optional[float]
    def __init__(self, lower: Optional[float] = ..., upper: Optional[float] = ...) -> None: ...


class MeasurementVal:
    unit: str
    value: float
    def __init__(self, unit: str, value: float) -> None: ...


Value = Union[
    StringVal,
    IntVal,
    FloatVal,
    BoolVal,
    NullVal,
    SymbolVal,
    TaggedStringVal,
    ArrayVal,
    MapVal,
    RangeVal,
    MeasurementVal,
]


class Subject:
    identity: str
    labels: set[str]
    properties: dict[str, Value]
    def __init__(
        self,
        identity: str,
        labels: Optional[set[str]] = ...,
        properties: Optional[dict[str, Value]] = ...,
    ) -> None: ...
    @classmethod
    def from_id(cls, identity: str) -> "Subject": ...
    def with_label(self, label: str) -> "Subject": ...
    def with_property(self, name: str, value: Value) -> "Subject": ...


class Pattern(Generic[V]):
    value: V
    elements: list["Pattern[V]"]
    def __init__(self, value: V, elements: Optional[list["Pattern[V]"]] = ...) -> None: ...
    @classmethod
    def point(cls, value: V) -> "Pattern[V]": ...
    @classmethod
    def of(cls, value: V) -> "Pattern[V]": ...
    @classmethod
    def pattern(cls, value: V, elements: list["Pattern[V]"]) -> "Pattern[V]": ...
    @classmethod
    def from_list(cls, value: V, values: list[V]) -> "Pattern[V]": ...
    @classmethod
    def unfold(cls, expand: Callable[[A], tuple[V, list[A]]], seed: A) -> "Pattern[V]": ...
    @property
    def is_atomic(self) -> bool: ...
    @property
    def length(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def depth(self) -> int: ...
    def map(self, fn: Callable[[V], U]) -> "Pattern[U]": ...
    def fold(self, init: R, fn: Callable[[R, V], R]) -> R: ...
    def filter(self, predicate: Callable[["Pattern[V]"], bool]) -> list["Pattern[V]"]: ...
    def find_first(self, predicate: Callable[[V], bool]) -> Optional[V]: ...
    def extend(self, fn: Callable[["Pattern[V]"], U]) -> "Pattern[U]": ...
    def extract(self) -> V: ...
    def duplicate(self) -> "Pattern[Pattern[V]]": ...
    def values(self) -> list[V]: ...
    def any_value(self, predicate: Callable[[V], bool]) -> bool: ...
    def all_values(self, predicate: Callable[[V], bool]) -> bool: ...
    def matches(self, other: "Pattern[V]") -> bool: ...
    def contains(self, needle: "Pattern[V]") -> bool: ...
    def para(self, f: Callable[["Pattern[V]", list[R]], R]) -> R: ...
    def combine(self, other: "Pattern[V]", combine_values: Callable[[V, V], V]) -> "Pattern[V]": ...
    def depth_at(self) -> "Pattern[int]": ...
    def size_at(self) -> "Pattern[int]": ...
    def indices_at(self) -> "Pattern[list[int]]": ...
    def __iter__(self) -> Iterator["Pattern[V]"]: ...


def value_from_dict(d: object) -> Value: ...
def value_to_dict(v: Value) -> object: ...
def pattern_from_dict(d: dict[str, Any]) -> Pattern[Subject]: ...
def unfold(expand: Callable[[A], tuple[V, list[A]]], seed: A) -> Pattern[V]: ...

Substitution = Union[str, tuple[str, Pattern[Subject]]]

class GraphQuery:
    def nodes(self) -> list[Pattern[Subject]]: ...
    def relationships(self) -> list[Pattern[Subject]]: ...
    def source(self, rel: Pattern[Subject]) -> Optional[Pattern[Subject]]: ...
    def target(self, rel: Pattern[Subject]) -> Optional[Pattern[Subject]]: ...
    def incident_rels(self, node: Pattern[Subject]) -> list[Pattern[Subject]]: ...
    def degree(self, node: Pattern[Subject]) -> int: ...
    def node_by_id(self, identity: str) -> Optional[Pattern[Subject]]: ...
    def relationship_by_id(self, identity: str) -> Optional[Pattern[Subject]]: ...

def map_graph(
    graph: StandardGraph,
    mappers: dict[str, Callable[[Pattern[Subject]], Pattern[Subject]]],
) -> StandardGraph: ...
def map_all_graph(
    graph: StandardGraph,
    f: Callable[[Pattern[Subject]], Pattern[Subject]],
) -> StandardGraph: ...
def filter_graph(
    graph: StandardGraph,
    predicate: Callable[[str, Pattern[Subject]], bool],
    substitution: Substitution,
) -> StandardGraph: ...
def fold_graph(
    graph: StandardGraph,
    f: Callable[[str, Pattern[Subject]], R],
    empty: R,
    combine: Callable[[R, R], R],
) -> R: ...
def map_with_context(
    graph: StandardGraph,
    f: Callable[[GraphQuery, Pattern[Subject]], Pattern[Subject]],
) -> StandardGraph: ...
def para_graph(
    graph: StandardGraph,
    f: Callable[[GraphQuery, Pattern[Subject], dict[str, R]], R],
) -> dict[str, R]: ...


class StandardGraph:
    def __init__(self) -> None: ...
    @classmethod
    def from_patterns(cls, patterns: list[Pattern[Subject]]) -> "StandardGraph": ...
    @classmethod
    def from_gram(cls, input: str) -> "StandardGraph": ...
    @property
    def node_count(self) -> int: ...
    @property
    def relationship_count(self) -> int: ...
    @property
    def annotation_count(self) -> int: ...
    @property
    def walk_count(self) -> int: ...
    @property
    def is_empty(self) -> bool: ...
    @property
    def has_conflicts(self) -> bool: ...
    def nodes(self) -> Iterator[tuple[str, Pattern[Subject]]]: ...
    def relationships(self) -> Iterator[tuple[str, dict[str, Any]]]: ...
    def annotations(self) -> Iterator[tuple[str, Pattern[Subject]]]: ...
    def walks(self) -> Iterator[tuple[str, Pattern[Subject]]]: ...
    def other(self) -> list[Pattern[Subject]]: ...
    def node(self, id: str) -> Optional[Pattern[Subject]]: ...
    def relationship(self, id: str) -> Optional[dict[str, Any]]: ...
    def annotation(self, id: str) -> Optional[Pattern[Subject]]: ...
    def walk(self, id: str) -> Optional[Pattern[Subject]]: ...
    def source(self, rel_id: str) -> Optional[Pattern[Subject]]: ...
    def target(self, rel_id: str) -> Optional[Pattern[Subject]]: ...
    def neighbors(self, node_id: str) -> list[Pattern[Subject]]: ...
    def degree(self, node_id: str) -> int: ...
